{{- if .Values.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "common-chart.fullname" . }}
  labels:
    {{- include "common-chart.labels" . | nindent 4 }}
spec:
  entryPoints:
    {{- toYaml .Values.ingress.entryPoints | nindent 4 }}
  routes:
    - match: {{ .Values.ingress.match }}
      kind: Rule
      services:
        - name: {{ include "common-chart.fullname" . }}
          port: {{ .Values.service.port }}
{{- end }}
